/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlideSlideIndexRouteRouteImport } from './routes/slide.$slideIndex/route'
import { Route as SlideSlideIndexIndexRouteImport } from './routes/slide.$slideIndex/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideSlideIndexRouteRoute = SlideSlideIndexRouteRouteImport.update({
  id: '/slide/$slideIndex',
  path: '/slide/$slideIndex',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideSlideIndexIndexRoute = SlideSlideIndexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlideSlideIndexRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slide/$slideIndex': typeof SlideSlideIndexRouteRouteWithChildren
  '/slide/$slideIndex/': typeof SlideSlideIndexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slide/$slideIndex': typeof SlideSlideIndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slide/$slideIndex': typeof SlideSlideIndexRouteRouteWithChildren
  '/slide/$slideIndex/': typeof SlideSlideIndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slide/$slideIndex' | '/slide/$slideIndex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slide/$slideIndex'
  id: '__root__' | '/' | '/slide/$slideIndex' | '/slide/$slideIndex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlideSlideIndexRouteRoute: typeof SlideSlideIndexRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$slideIndex': {
      id: '/slide/$slideIndex'
      path: '/slide/$slideIndex'
      fullPath: '/slide/$slideIndex'
      preLoaderRoute: typeof SlideSlideIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$slideIndex/': {
      id: '/slide/$slideIndex/'
      path: '/'
      fullPath: '/slide/$slideIndex/'
      preLoaderRoute: typeof SlideSlideIndexIndexRouteImport
      parentRoute: typeof SlideSlideIndexRouteRoute
    }
  }
}

interface SlideSlideIndexRouteRouteChildren {
  SlideSlideIndexIndexRoute: typeof SlideSlideIndexIndexRoute
}

const SlideSlideIndexRouteRouteChildren: SlideSlideIndexRouteRouteChildren = {
  SlideSlideIndexIndexRoute: SlideSlideIndexIndexRoute,
}

const SlideSlideIndexRouteRouteWithChildren =
  SlideSlideIndexRouteRoute._addFileChildren(SlideSlideIndexRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlideSlideIndexRouteRoute: SlideSlideIndexRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
